export const actionTypes = {
	CREATE: 'CREATE',
	UPDATE: 'UPDATE',
	DELETE: 'DELETE',
	FETCH_ALL: 'FETCH_ALL',
	LIKE: 'LIKE',
	AUTH: 'AUTH',
	LOGOUT: 'LOGOUT',
	FETCH_BY_SEARCH: 'FETCH_BY_SEARCH',
	START_LOADING: 'START_LOADING',
	END_LOADING: 'END_LOADING',
	FETCH_POST: 'FETCH_POST'
};
